---
#-------------------------------
# General Site Settings

#title: Kross
logo:
author: themefisher
description: this is meta description
email: andrielly.moraespereira@gmail.com
phone:  985612125
address: Belém - PA, Brasil
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - #{ name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Andrielly <br> Data Science

social:
  - { icon: "ti-kaggle", link: "https://www.kaggle.com/andrielly" }
  - { icon: "ti-github", link: "https://github.com/andriellymoraespereira" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/andriellymoraespereira" }
  - { icon: "ti-medium", link: "https://medium.com/@andrielly.moraespereira" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: 

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: ""

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: ""

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: ""

# My Team Section
#team:
  #- title: "Jack Schenziwe"
    #image: "assets/images/team/member-1.png"
  #designation: "Project Manager"

  #- title: "Julias Carlie"
   # image: "assets/images/team/member-2.png"
    #designation: "Web Developer"

  #- title: "John Doe"
   # image: "assets/images/team/member-3.png"
    #designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Python, color: "#fdb157", value: "90%" }
  - { name: rStudio, color: "#9473e6", value: "90%" }
  - { name: GitHub, color: "#bdecf6", value: "80%" }
  - { name: SQL, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Programa de Mentoria KaggleX BIPOC,
      icon: "MP2.png",
      date: "Dez 2022 - Mar 2023",
      organization: "WEBEX",
    }
  #- {
      #name: UX & UI Designer,
      #icon: "icon-2.png",
      #date: "Mar 2009 - Aug 2014",
      #organization: "AUGMEDIX",
    #}
  #- {
      #name: Senior UI Designer,
      #icon: "icon-3.png",
      #date: "Sep 2014 - Present",
      #organization: "THEMEFISHER",
    #}

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Bacharelado em Estatística,
      date: "2021",
      organization: "Universidade Federal do Pará",
    }
  - {
      name: Formação em cientista de Dados,
      date: "em andamento",
      organization: "Data Science Academy",
    }
  #- {
      #name: Higher Secondary Certificat,
      #date: "2000",
      #organization: "Cardiff School",
    #}
  #- {
      #name: Secondary School Certificate,
      #date: "1998",
      #organization: "Cardiff School",
    #}

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: Estatística,
      icon: ti-palette,
      description: "A estatística é o campo da matemática que relaciona fatos e números em que há um conjunto de métodos que nos possibilita coletar dados e analisá-los, assim sendo possível realizar alguma interpretação deles. A estatística é dividida em duas partes: descritiva e inferencial.",
      active: ,# Add true to select section
    }
  - {
      name: Análise de Dados,
      icon: ti-vector,
      description: "Análise de dados é o processo de aplicação de técnicas estatísticas e lógicas para avaliar informações obtidas a partir de determinados processos. O principal objetivo da prática é extrair informações úteis a partir dos dados.",
      active: true, # Add true to select section
    }
  - {
      name: Ciência de Dados,
      icon: ti-panel,
      description: "A ciência de dados é o estudo dos dados para extrair insights significativos para os negócios. Ela é uma abordagem multidisciplinar que combina princípios e práticas das áreas de matemática, estatística, inteligência artificial e engenharia da computação para analisar grandes quantidades de dados.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "https://github.com/andriellymoraespereira/analise_Regressao"

 
# Portfolio Page
#portfolio-label:
  #- { title: "UI/UX Design", type: "design" }
  #- { title: "BRANDING", type: "branding" }
  #- { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "https://github.com/andriellymoraespereira/analise_Regressao"
    #portfolio-type:
      #- type: "design"
      #- type: "illustration"

#- image: "assets/images/portfolio/item-2.png"
    #url: "#"
    #portfolio-type:
      #- type: "branding"

  #- image: "assets/images/portfolio/item-3.png"
   # url: "#"
    #portfolio-type:
      #- type: "illustration"

  #- image: "assets/images/portfolio/item-6.png"
    #url: "#"
    #portfolio-type:
     # - type: "design"
      #- type: "branding"

  #- image: "assets/images/portfolio/item-8.png"
    #url: "#"
    #portfolio-type:
      #- type: "illustration"

  #- image: "assets/images/portfolio/item-5.png"
    #url: "#"
    #portfolio-type:
     # - type: "design"

  #- image: "assets/images/portfolio/item-1.png"
   # url: "#"
    #portfolio-type:
     # - type: "branding"

 
#-------------------------------
# Testimonials Section

#testimonial-items:
  #- name: "Andrielly Pereira"
   # image: "assets/images/testimonial/client-1.png"
    #designation: "CEO, Funder"
    #content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  #- name: "Jesica Gomez"
   # image: "assets/images/testimonial/client-1.png"
    #designation: "CEO, Funder"
    #content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  #- name: "Jesica Gomez"
   # image: "assets/images/testimonial/client-1.png"
    #designation: "CEO, Funder"
    #content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


contact-title: Contact Info
contact-email: andrielly.moraespereira@gmail.com
